/* Assessment report — AI-generated summary with mandatory disclaimer + CTA. */

function AssessmentReportScreen() {
  return (
    <MTScreen>
      <MTTopBar
        left={<MTRoundIcon><svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="#0E1726" strokeWidth={2.4} strokeLinecap="round"><path d="M6 6l12 12M6 18L18 6"/></svg></MTRoundIcon>}
        title="Assessment Report"
      />
      <div style={{ padding: '0 16px 110px' }}>
        <div style={{ marginBottom: 12 }}>
          <MTAIPill label="AI-generated summary" size="md" />
        </div>

        <MTCard padding={20} radius={20}>
          <div style={{ fontSize: 19, fontWeight: 800, color: '#0E1726' }}>Your activity assessment results</div>
          <div style={{ marginTop: 8, fontSize: 14, color: '#6B7280' }}>
            Overall balance: <span style={{ fontWeight: 700, color: '#0E1726' }}>Moderate (72%)</span>
          </div>

          {/* Big number summary */}
          <div style={{ marginTop: 14, padding: 14, background: '#FBF5EF', borderRadius: 16,
            display: 'flex', alignItems: 'center', gap: 16 }}>
            <div style={{ fontSize: 44, fontWeight: 800, lineHeight: 1, color: '#F97316', letterSpacing: '-0.03em' }}>
              72<span style={{ fontSize: 24, color: '#C9531A' }}>%</span>
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 700, color: '#0E1726' }}>Mild–moderate stress</div>
              <div style={{ fontSize: 11, color: '#6B7280', marginTop: 2 }}>Higher than 60% baseline · Manageable</div>
            </div>
          </div>

          <div style={{ marginTop: 16, fontSize: 14, color: '#1C2433', lineHeight: 1.6 }}>
            <p style={{ margin: 0 }}>Based on your responses, your recent <b>stress and activity levels</b> suggest you are managing most days reasonably well, but there are clear signs of mental fatigue and emotional overload on busier days.</p>
            <p style={{ margin: '12px 0 0' }}>You reported <b>frequent worry and restlessness</b>, especially in the evenings, along with occasional difficulty relaxing. At the same time, you also identified small, consistent sources of support—like routines, relationships, or hobbies—that are helping you stay grounded.</p>
            <p style={{ margin: '12px 0 0' }}>Overall, your pattern points to a <b>mild to moderate level of stress (around 60–75%)</b>. With some structured support, there is strong potential to bring this down and improve your sense of ease and control in daily life.</p>
          </div>

          <div style={{ marginTop: 16, paddingTop: 14, borderTop: '1px solid #ECE6DE',
            fontSize: 12, color: '#6B7280', lineHeight: 1.5 }}>
            This summary is generated by AI based on your answers. It is <span style={{ color: '#C9531A', fontWeight: 700 }}>not a diagnosis</span> and should be used as a reflection aid, not as medical advice.
          </div>
        </MTCard>

        <div style={{ marginTop: 18 }}>
          <MTButton variant="primary" size="lg" full
            icon={<svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 9h18M8 3v4M16 3v4"/></svg>}
          >Book appointment with a specialist</MTButton>
          <div style={{ marginTop: 10, fontSize: 12, color: '#6B7280', textAlign: 'center', lineHeight: 1.5 }}>
            You can share this report with a mental health professional to explore next steps together.
          </div>
        </div>
      </div>

      <MTTabBar active="explore" />
    </MTScreen>
  );
}

Object.assign(window, { AssessmentReportScreen });
